### ISSUE TITLE
paginationMaxLinesPerPage on thumbnailHeight not 'auto'

### ISSUE THREAD

**Issue by TuSKan** [Kris-B/nanoGALLERY#100]
I would like to use the *paginationMaxLinesPerPage* attribute when the *thumbnailHeight* is set a value (not *'auto'*), because you have a fixed Height perline.
It would be great to work in that situation.

Because without it, the nanoGallery was break my paralax/stellar image divider.

**Comment by Kris-B** [comment]
You can use this attribute when `thumbnailHeight` and `thumbnailWidth` are set to a numeric value.
If one is set to `auto` then it's not possible.
