### ISSUE TITLE
Not Showing nanoPhotosProvider

### ISSUE THREAD

**Issue by Junjie-Chen** [Kris-B/nanoGALLERY#102]
Hey, Kris:

               I downloaded all the php files of nanoPhotosProvider and uploaded to my server. 
               Photos are stored in nanoPhotosContent in folders (=albums). 
               nanoGallery for jQuery, a div element and script are also included in my html page, but no gallery shows up by the point. 
               Could you help me detect which part is going wrong? Very appreciate your time! 
               Attached is my jsfiddle: https://jsfiddle.net/5pptLbee/8/

**Comment by Kris-B** [comment]
please see https://github.com/Kris-B/nanoPhotosProvider/issues/10
