### ISSUE TITLE
nanoGALLERY not honoring the EXIF Orientation tag?

### ISSUE THREAD

**Issue by dhwalker** [Kris-B/nanoGALLERY#103]
I'm just starting to use nanoGALLERY, and I've found that it doesn't seem to honor the Orientation EXIF tag in the image file.  Photos with a vertical orientation are displayed on their side.  Am I missing something, or is this a limitation?

David

**Comment by Kris-B** [comment]
nG doesn't manage the display orientation. The image display is handled by the browser, and as far as I know exif orientation is ignored by it.

**Comment by wuhi** [comment]
any news on this? i did some tests with CSS setting image-orientation: from-image;
this fixes the orientation-issue, but nanogallery adds width and height styles manually. so they are switched.
