### ISSUE TITLE
How to give the ".nanoGalleryThumbnailContainer" the data-ngid from the original link?

### ISSUE THREAD

**Issue by DioVayne** [Kris-B/nanoGALLERY#104]
In the original container a link is written with a href, data-ngid and data-ngthumb. I want to be able to connect the processed code with additional functions by targeting the .nanoGalleryThumbnailContainer but there is no reference to the original ID.

I hope I'm making myself clear.

**Comment by Kris-B** [comment]
See PR #105 
;-)
