### ISSUE TITLE
Nano gallery refuses to show images on screen

### ISSUE THREAD

**Issue by jitunair18** [Kris-B/nanoGALLERY#109]
My html snippet is as below with some images on my pc.

   <div id="nanoGallery3">
                <a href="images1/joinhands.jpg" data-ngthumb="images1/computersforkids.png">Computers For Kids</a>
                <a href="images1/digitalindia.jpg" data-ngthumb="images1/digitalindia.jpg">Digital India</a>
                <a href="images1/luckytoread.jpg" data-ngthumb="images1/luckytoread.jpg">Lucky to Read</a>
                <a href="images1/righttoeducation.jpg" data-ngthumb="images1/righttoeducation.jpg">Right To Education</a>
                <a href="images1/soccer_kids.jpg" data-ngthumb="images1/soccer_kids.jpg">Soccer Kids</a>
                <a href="images1/sportsforkids.png" data-ngthumb="images1/sportsforkids.png">Sports For Kids</a>

            </div>

My js is directly from the website:
 jQuery(document).ready(function () {
        jQuery("#nanoGallery3").nanoGallery({
            
            itemsBaseURL: 'http://nanogallery.brisbois.fr/demonstration/'
        });
    });

Attaching snapshot which shows state of my gallery.
Please provide some inputs on why the images are not turning up.
I am looking them up on Chrome and Mozilla
![nanogallery](https://cloud.githubusercontent.com/assets/10362761/13906667/a716b5ae-eeb2-11e5-9032-74f6fd008941.jpg)

**Comment by Kris-B** [comment]
Your `itemsBaseURL`points to `http://nanogallery.brisbois.fr/demonstration/`-> but your images do not exist on this URL.

**Comment by jitunair18** [comment]
Kris,
The images are currently on my local drive. Could you please tell me what my next steps should be?
Thank you so much for pointing this out to me but I am not exactly sure what my next steps should be here.
Shreejit

**Comment by Kris-B** [comment]
You need to store your images on a webserver and then adjust `itemsBaseURL` to point to them.
