### ISSUE TITLE
Commercial License Clarification

### ISSUE THREAD

**Issue by al-debaran** [Kris-B/nanoGALLERY#111]
Hi Kris-B 

I have 2  questions  : 

1) I’m  interested in  using  your nanoGallery commercially. I have read the commercial license conditions at http://nanogallery.brisbois.fr/ , but I want to clarify if it covers the following .. I am (starting out as) a web designer, doing websites for other persons as a paid service. If such a website that I do is also a commercial website for the website owner,  then if I buy one multi-site OEM license for 90 Euro, will this then cover any such number of commercial websites that I provide,  and without  the website  owner having to pay for any further  license  ?         

2) Have you had a chance to look at my further question under post “Question Ultra Clean Look”,  about if it is possible to show just showing one thumb instead of all thumbs ?  Where if you click this thumb  then you go straight to the main image view.   I just want to know  - yes or no – If it is possible, or if I can do something to make it happen .. .. 

Many thanks 

Al-Debaran

**Comment by Kris-B** [comment]
Hi @al-debaran,

The OEM license is a one time fee. There are no additional costs, even for the website owner.

Please check my answer on your request #108 

Best regards

**Comment by al-debaran** [comment]
Hi Kris-B

OK  .. All clear.  Many thanks

Al-Debaran
