### ISSUE TITLE
How to disable imagedescription but not gallerydescription?

### ISSUE THREAD

**Issue by mgk89** [Kris-B/nanoGALLERY#112]
Hi,
what a great work you did!

by this code I have the perfect settings for my gallery-preview, but I would like to disable the imagedescription (DSC07644, etc.)
how can that be done? Is it by thumbnailL1? I tried, but nothing happened.

Thanks in advance!
```
  thumbnailHoverEffect:[{name: 'imageScale150', duration:700}],
		   	thumbnailLabel: {
            position: 'overImageOnBottom',
            display: true,
            displayDescription: true,
            titleMaxLength: 25,
            hideIcons: true,
            align: 'center',
            itemsCount: 'description',
			},
			
				
			i18n: { 
			
			thumbnailLabelItemsCountPart1: '',
			thumbnailImageDescription: 'Klicken zum Vergr&ouml;&szlig;ern',
			breadcrumbHome: 'alle Gallerien'
		     }
```

**Comment by Kris-B** [comment]
Hi, did you try to set `displayDescription` to `false`?

**Comment by Kris-B** [comment]
read your request too fast... sorry

yes, you can use something like : 
```
   ...
   thumbnailL1Label.displayDescription: false,
   ...
```

This will hide the description on the first level (albums)

**Comment by mgk89** [comment]
hi,

thanks for your reply!

actually I want it the other way: 

Description for the galleries is fine (is working right now), but I want to hide the description (or to be exactly the filename) for the thumbnails. I would like to keep the description `thumbnailImageDescription: 'Klicken zum Vergr&ouml;&szlig;ern',` but not the 'DSC8541' or whatever.

thanks for your help!

**Comment by Kris-B** [comment]
Actually, I had corrected m'y answer directly on github, but you probably
got the uncorrected one...
Can you please check on the github page?

**Comment by Kris-B** [comment]
Please check the source code of the demo "Pagination 1 row" on http://nanogallery.brisbois.fr/#examples

**Comment by mgk89** [comment]
hi,
thank you for your answer.

thumbnailL1Label: {displayDescription: true},

will actually cause that for the image-thumbnails the description   thumbnailImageDescription: 'Klicken zum Vergr&ouml;&szlig;ern', is not shown anymore, but the image name "DSC 12345" is still shown.
I'm not sure if I can explain what I mean :) I would like to have that description text, but not the filename.

thanks for you help!

**Comment by Kris-B** [comment]
can you please create a codepen ?

**Comment by mgk89** [comment]
hi,

I actually could make it work as I wanted by:

`display: false,
 displayDescription: false, `

and

`thumbnailL1Label: {display: true, displayDescription: false},`
