### ISSUE TITLE
Long flickr description cropped

### ISSUE THREAD

**Issue by webrunner74** [Kris-B/nanoGALLERY#114]
Hello, I got an issue with my flickr albums. When opening an image where the description is long, the description div is too big and goes outside the image, and gets cropped:

http://www.interieur-altitude.com/page/luminaires#nanogallery/nanoGallery1/72157665391809960/25722721031

Is it a nanoGALLERY issue?

**Comment by Kris-B** [comment]
The width of the description is limited to the width of the image.
You can use `viewerToolbar: {style : 'fullWidth'}` to use the full screen width.

**Comment by webrunner74** [comment]
Merci beaucoup !

2016-05-03 15:08 GMT+02:00 Christophe Brisbois <notifications@github.com>:

> viewerToolbar: {style : 'fullWidth'}




Thierry Milherou

*Toutes mes références sur http://webrunner.org/page/references-sites
<http://webrunner.org/page/references-sites>*

   - *Chef de projet web, Office de Tourisme de La Clusaz*
   - *Webmaster indépendant // Webrunner - création de sites internet -
   graphisme - photo - montage vidéo*

**Comment by Kris-B** [comment]
pas de soucis ;-)
