### ISSUE TITLE
error when image fail to load

### ISSUE THREAD

**Issue by PrakashDR** [Kris-B/nanoGALLERY#118]
when image fail to load (internet is not connected) it shows error. How to stop these error

**Comment by Kris-B** [comment]
Can you give me the error message?

**Comment by PrakashDR** [comment]
With Regards
Prakash D
Smabes Solutions Private Limited

**Comment by Kris-B** [comment]
???



2016-05-17 8:01 GMT+02:00 PrakashDR <notifications@github.com>:

> With Regards
> Prakash D
> Smabes Solutions Private Limited
>
> On Fri, May 13, 2016 at 2:13 AM, Christophe Brisbois <
