### ISSUE TITLE
sliding animation artifact

### ISSUE THREAD

**Issue by msharp1** [Kris-B/nanoGALLERY#121]
Hello,

Running Ubuntu 16.04 LTS, firefox 47 on a desktop PC.

Here is what's happen when I move to _next_ image on http://nanophotosprovider.herokuapp.com/demonstration/heroku.html 

![bug-animation-nano](https://cloud.githubusercontent.com/assets/5676327/16540469/3b304976-4066-11e6-8921-c0ae3a70c9eb.jpg)

The same happen when I move to _previous_ image but this time on the left side of the image

**Comment by Kris-B** [comment]
please check the new major release: http://nanogallery2.nanostudio.org
