### ISSUE TITLE
Google killed Picasa / convert to Google Photos

### ISSUE THREAD

**Issue by impresio** [Kris-B/nanoGALLERY#122]
Hi Kris, as the first many thanks for ur great work with this gallery!! 

Unfortunately G made some changes and killed picasa (https://picasa.google.com/). So its now showing only the galleries publisched before 01.06 (last i can see is from 28.05). Albums publisched after (e.g 11.06) are no more visible :/

Please tel me know when/if will be some next update ready. 

Thanks!

**Comment by Kris-B** [comment]
Hi impresio ;-)

At this time, it seems only possible to create non public albums in google photos.
Some tools exist to change the visibility of an album.
For example:
- Ozio Gallery has this feature in the admin user interface - http://extensions.joomla.org/extension/ozio-gallery
- Sven Bluege wrote this tool - http://www.svenbluege.de/picasa/v1.1/

hope this helps

**Comment by mpschr** [comment]
@Kris-B could it be solved by directly loading one album with the sharing link somehow?

**Comment by WoodyF4u** [comment]
I connect myself in this topic, cause I do have the same issue with the albums in Google Photos.
There is no option to create an album as Public anymore.
So extensions like Ozio Gallery and Phoca Gallery can no longer be used for new albums.
Only existing albums are still vissible foor website visitors.

I realy hope that the developers of Ozio Galery can nfind the solution for this.

**Comment by AlexRed** [comment]
Hello WoodyF4u, the solutions for Ozio Gallery is already out. Please use the last version and read the istructions: http://www.opensourcesolutions.es/en/ext/ozio-gallery.html#Instructions

**Comment by impresio** [comment]
This Svens Blueges tool - http://www.svenbluege.de/picasa/v1.1/  still works like a charm.

Thank you Kris-B btw :)

**Comment by snap10** [comment]
svenbluege's workaround is no longer working, since google cut the API he used, according to his update from Update

> 02/09/2017 Google has made its promisse true. It is not longer possible to change album properties through the API. That means you can't change any of the albums below. But there is hope! I found a way how you can even use protected albums in Event Gallery so there is no need to change anything. I'll keep you posted. 

Any plans on integrating a method to use share-links for the ozio-gallery?
