### ISSUE TITLE
how to fix? 

### ISSUE THREAD

**Issue by srt56** [Kris-B/nanoGALLERY#124]
![2016-07-14_081148](https://cloud.githubusercontent.com/assets/6491418/16828713/088cdece-499b-11e6-9111-e06ed2952878.png)

question in the screenshot

thanks

**Comment by srt56** [comment]
Kris-B, Hi.
how to fix error?

**Comment by Kris-B** [comment]
please swicth to nanogallery2 (http://nanogallery2.nanostudio.org)
