### ISSUE TITLE
photostream limit

### ISSUE THREAD

**Issue by prostranstvo** [Kris-B/nanoGALLERY#130]
Thank you for such a great gallery!

Could you please let me know how to overcome the "limited to 500 photos" photostream display in nanoGallery?

I'd like to use photostream root rather than an album for the reason of automation. ( example: Group of people sends pictures to a special email that places images into a photostream's root. )

Thanks,
Ilya

**Comment by Kris-B** [comment]
actually, this is not a nanogallery limit, but rather a limitation with Flickr/Google Photos.
will be solved in a future release

**Comment by Kris-B** [comment]
a workaround has been implemented in nanogallery2 - http://nanogallery2.nanostudio.org

**Comment by prostranstvo** [comment]
That's an amazing update!
Thank you for your creativity and dedication.

**Comment by Kris-B** [comment]
;-)
