### ISSUE TITLE
Pagination Not Working

### ISSUE THREAD

**Issue by AmrataRamchandani** [Kris-B/nanoGALLERY#131]
![capture](https://cloud.githubusercontent.com/assets/18703768/19219508/d99ad80a-8e32-11e6-8478-704ff9bf3a38.PNG)
$(document).ready(function () {
          $("#nanoGallery2").nanoGallery({
              kind: 'picasa',
              userID: 'XXXX',
              thumbnailWidth: 100,
              thumbnailHeight: 100,
              paginationVisiblePages:5,
              paginationMaxLinesPerPage:5,	
              i18n:{ breadcrumbHome: 'Lyrics' }
              
              
              
          });
      });

**Comment by Kris-B** [comment]
please test with `paginationMaxLinesPerPage: 1`
