### ISSUE TITLE
looking for beta tester - nanogallery2

### ISSUE THREAD

**Issue by Kris-B** [Kris-B/nanoGALLERY#132]
nanoGALLERY is available since 2013 and 49 versions have been released on github.

It's now time for a new major release. It will be called <b>nanogallery2</b>.

You can check a preview: http://nanogallery2.nanostudio.org

I'm looking for some beta testers. If you're interested, just mail me: chr@brisbois.fr
The full documentation will only be provided per mail.

**Comment by macsupport** [comment]
Emailed a few times but no response. I am an OEM license holder, any chance of beta testing?

**Comment by Kris-B** [comment]
Sure! I just sent it to you.
Sorry for the delay, I had a technical issue with my mail account...

**Comment by Kris-B** [comment]
The restricted beta phase is now complete.
nanogallery2 is now accessible to everyone: http://nanogallery2.nanostudio.org/

For professional license holders, please note that the upgrade to nanogallery2 doesn't require any fee.
