### ISSUE TITLE
Dynamically Add and Remove Items

### ISSUE THREAD

**Issue by woojoo666** [Kris-B/nanoGALLERY#133]
Is there a way to add/remove items from the gallery, and then refresh the gallery?

I tried just modifying the "items" array and using nanoGallery('reload'), but it didn't change anything: [CodePen](http://codepen.io/anon/pen/YNpwxo)

Perhaps it only works with inline elements, and not javascript arrays?

**Comment by Kris-B** [comment]
This feature is available in nanogallery2 v1.0.0

Here's a codepen example: http://codepen.io/Kris-B/pen/wJKowg
