### ISSUE TITLE
Enable zoom on mobile? 

### ISSUE THREAD

**Issue by mgk89** [Kris-B/nanoGALLERY#134]
Hi,
Is there a chance to enable two-finger zoom on the images or double-tip zoom as known from galleries in Android?
Thanks a Lot

**Comment by Kris-B** [comment]
Hey, actually, this feature is available in nanogallery2: https://github.com/nanostudio-org/nanogallery2

**Comment by rradjabi** [comment]
Kris, I have a similar request. Can you post the link to a site where I can verify zoom? I don't think it works on nanogallery.brisbois.fr on my phone.

**Comment by Kris-B** [comment]
this feature is available in the new version: nanogallery2
please upgrade

https://nanogallery2.nanostudio.org/
