### ISSUE TITLE
Download Images on Mobile

### ISSUE THREAD

**Issue by rradjabi** [Kris-B/nanoGALLERY#135]
Is there an option to allow click-and-hold download of images (while open in Lightbox) on mobile devices? This is common for images most other sites. In addition, is there an option to enable a download button? Preferably this would download a medium quality image (same as displayed).

Thank you,
Ryan

**Comment by Kris-B** [comment]
this feature is available in the new version: nanogallery2
please upgrade

https://nanogallery2.nanostudio.org/

**Comment by rradjabi** [comment]
Hi Kris, 
Do you have instructions for upgrading to nanogallery2? I already have a working site using version 1. Are there just a few files that can be replaced? 
Ryan

**Comment by Kris-B** [comment]
Hi Ryan,
you have to replace the old files with the new ones and then you may need to change some options: https://nanogallery2.nanostudio.org/documentation.html#ngy2_upgrade
