### ISSUE TITLE
Parameter to upsacle image to fullscreen

### ISSUE THREAD

**Issue by Kris-B** [Kris-B/nanoGALLERY#38]

**Comment by DesignMitZweiS** [comment]
when I use nanoGallery with my flickr account, fullscreen images are loaded like: img-number_z.jpg
this are images with the screensize of 640x ... to get bigger images one can change the name to img-number_b.jpg

here is an example .. try both images pls.

smaller version(640x...)
https://farm5.staticflickr.com/4150/5410735417_c53130522d_z.jpg

bigger version (1024x...)
https://farm5.staticflickr.com/4150/5410735417_c53130522d_b.jpg


is there a way I can control it in my script?

**Comment by Kris-B** [comment]
Actually nanoGALLERY will use the version of the image with the size that fits to the screen of the browser. So, on small screen a low resolution version is used, and on high resolution screen, a high resolution version is used.
By this way, the bandwidth is optimized.

**Comment by helb** [comment]
This seems to be sort of broken here, i still get 640x… photos in 1920x1200 browser window (original image is 1440x…). :(

```javascript
$("#photos").nanoGallery({
  kind: 'flickr',
  userID: …,
  photoset: …,
  thumbnailLazyLoad:  true,
  locationHash: false,
  thumbnailWidth: 128,
  thumbnailHeight: "auto",
  thumbnailAlignment: "left",
  colorScheme: "light",
  touchAnimation:  false,
  thumbnailLabel:  {
    display: false
  },
  viewerToolbar:  {
    style: "stuckImage",
    autoMinimize: 500,
    standard: "label, previousButton, pageCounter, nextButton, playPauseButton, fullscreenButton",
    minimized: "label, minimizeButton, playPauseButton, closeButton",
  },
  displayBreadcrumb: false
});
```

I tried to mess with `breakpointSize*` and `flickrSkipOriginal` but with no success.

**Comment by Kris-B** [comment]
I was not able to reproduce this issue...
Can you please check the first gallery on http://nanogallery.brisbois.fr ?
What is the size of the displayed photos?

**Comment by DesignMitZweiS** [comment]
Hi Kris,

your gallery example is working fine for me. it shows fullscreen images.
however I've made you a pen to see my problem: http://codepen.io/DesignMitZweiS/pen/ByvdwW

I'm using the latest CDN versions in this pen. I'm not getting any fullscreen pictures.

**Comment by helb** [comment]
I played with it a bit and it seems to me that Flickr does this (sending only smaller sizes to nanoGallery) with photos without EXIF. Seems weird, I know. Can't confirm it with @DesignMitZweiS' photos now, Flickr gives me me the "bad panda" error page today…
I no longer use nanoGallery in production, as I built my own fast–stupid–simple gallery just for single Flickr sets (it just pulls various photo sizes into responsive `<figure>` and lets the browser decide which one to use), but will look into this over the weekend.

**Comment by DesignMitZweiS** [comment]
@helb hm, almost all of my pictures have EXIF information. I also checked my settings in flickr. I've allowed users to get the original image size and also maximum size. I really can't understand why it's not working for me :-/

**Comment by Kris-B** [comment]
I found the problem: image size L (1024 pixels) was ignored...

Fixed in v5.5.3.

@DesignMitZweiS @helb : Many thanks for your help!

**Comment by DesignMitZweiS** [comment]
awesome work. you fixed it! :)
thanks a ton!

**Comment by Kris-B** [comment]
@DesignMitZweiS thanks for your feedback!
;-)
