### ISSUE TITLE
Question: How can I add pictures to the image library dynamically?

### ISSUE THREAD

**Issue by jheinitz** [Kris-B/nanoGALLERY#50]
Hello Kris!

Great work! Thanks for putting your efforts in here. 

I just started to expore the features of nanoGALLERY. I have a directory on my webserver and would like to fill the nanoGALLERY image library dynamically from the content of the directory. i can also imaging to have one directory containing the images and a second directory with the thumbnails. 

Is there a way to achieve this?

Best regards

Jens

**Comment by Kris-B** [comment]
Hi Jens, sorry for this late reply...

I made a new version of the PHP application. You can find it now at: https://github.com/Kris-B/nanoPhotosProvider
The data structure is now simpler and the thumbnails are generated automatically.

To test it, you'll have to use the `jquery.nanogallery.js` version from the `demonstration` folder.

**Comment by Kris-B** [comment]
This feature is now provided by
https://github.com/Kris-B/nanoPhotosProvider

thx.
