### ISSUE TITLE
Unable to display picture containing special characters like äöü

### ISSUE THREAD

**Issue by jheinitz** [Kris-B/nanoGALLERY#54]
Hello,

I'm trying to automate the creation of the HTML page containing a Gallery using a shell script by going through all files in a given directory. I made a lot of progress and it works as expected. 

However, some of my pictures and thumbnails are not displayed. I came across the fact that all these items have in common that they contain atleast one of the characters äöüÄÖÜß. Is there anything I can to to make it work without renaming files from ö to oe?

My encoding is: ISO-8859-1:1998 (Latin-1, West Europe)

Kind regards

Jens

**Comment by Kris-B** [comment]
If this is still an issue for you, please open a new issue in the repo https://github.com/Kris-B/nanoPhotosProvider

thx.
