### ISSUE TITLE
Different title/description options per level

### ISSUE THREAD

**Issue by klous-1** [Kris-B/nanoGALLERY#57]
It would be nice if it was possible to set different title and description options for a multilevel gallery.

Having the title and description shown is nice on the level 1 (album cover) thumbnails, but - in some cases - not so good for the album's content images, which could be some ugly number assigned from picasa or wherever, and better off hidden.

Is there a way to do this that I'm missing, or could this be added in the same way we have thumbnailL1Width, maybe thumbnailL1Label?

Thanks

**Comment by Kris-B** [comment]
Since v5.4.0, you can now use these new options: `thumbnailL1Label`, `thumbnailL1HoverEffect`, `touchAnimationL1`

Documentation will be updated in a few days.
Sorry for the long delay...

**Comment by klous-1** [comment]
Brilliant, thanks Christophe :clap:

**Comment by Kris-B** [comment]
;-)
