### ISSUE TITLE
Drupal

### ISSUE THREAD

**Issue by PaulaThoelen** [Kris-B/nanoGALLERY#59]
I like the nanoGallery and I want to use it on a Drupal-website for showing Picasa-pictures. Only I don't know how to do this. I have now experience with jQuery in combination with Drupal yet. Where will I have to put the documents? And what are the next steps?
On the Drupal.org-website I can find some things about using jQuery, but I don't understand it very well (I'm Dutch-speaking). Can someone show me the way?

**Comment by Kris-B** [comment]
@PaulaThoelen did you found a solution? If yes, it would be nice to share it here. Thx!

**Comment by PaulaThoelen** [comment]
No, not yet. I don't think I can find the right solution on my own. Maybe I'll have to wait for Drupal 8. I'm still trying (now and then), but it will take more time I guess.

**Comment by Kris-B** [comment]
ok, thanks for your feedback!
