### ISSUE TITLE
Slideshow timer

### ISSUE THREAD

**Issue by klous-1** [Kris-B/nanoGALLERY#60]
Hello,

When viewing the slideshow, if you click "play" the timer (delay) begins counting even if the image isn't loaded, in some cases the loading timer is shown, slides off screen (without seeing the image), starts loading the next one, more spinning wheel loading image...and so on.

Might be better to have the counter begin once the image is loaded?

**Comment by Kris-B** [comment]
maybe a bit late, but it's now implemented in nanogallery2 (http://nanogallery2.nanostudio.org)

**Comment by klous-1** [comment]
Hahaha!  Thanks for remembering!


________________________________

**Comment by Kris-B** [comment]
;-)
