### ISSUE TITLE
Initial display as block instead of inline

### ISSUE THREAD

**Issue by blondie2world** [Kris-B/nanoGALLERY#61]
Hey, 
I'm a webdesign rookie, so I probably made some stupid mistake.
I 've set up a nanoGallery inside a bootstrap modal.
But my Flick'r folders don't show up in a row initially. The folders appear each on a new line (inline).
After clicking through the galleries and returning to the main gallery, the thumbnails show up correctly.
Any ideas on how to fix this?
Thanks in advance!
Greetings

**Comment by Kris-B** [comment]
Hi,
Can you give me the URL of your page?

**Comment by blondie2world** [comment]
Hey, 
ingeturelinckx.com  (photography section)
Thank you for your help!
Grtz

**Comment by Kris-B** [comment]
Hi!
The container of the gallery is hidden when the gallery is first build, so the conatiner's width cannot nbe retrieved.
Workaround: build the gallery not on document ready, but just after the container is displaued.

**Comment by blondie2world** [comment]
Hey, 
this is a logical explanation. I'll fix that!
thank you very much for this solid solution!
Great app!!

**Comment by Kris-B** [comment]
;-)
