### ISSUE TITLE
Can anybody help me with bootstrap integration?

### ISSUE THREAD

**Issue by mixedsign** [Kris-B/nanoGALLERY#62]
Hi, I'm absolute beginner with code writing.
I'm trying to integrate nanoGallery in bootstrap, but something is not working.

With blank page i have not a problem:
http://test.vanyart.com/

But wen I'm trying to paste in bootstrap something is not working:
http://nano.vanyart.com/ - the gallery missing

I'm uploading the code here:
https://github.com/mixedsign/nanoGalleryBootstrap

I will very grateful if somebody help to solve this problem

**Comment by Kris-B** [comment]
Hi, sorry for the late reply, I didn't notice the changes in your request...

Jquery is included twice in your page. Please try to remove one of them.

**Comment by mixedsign** [comment]
Great! Thank you very much!
