### ISSUE TITLE
thumbnailLabel allows HTML elements but interferes with clicks on them

### ISSUE THREAD

**Issue by mudnug** [Kris-B/nanoGALLERY#66]
In my implementation, I am wanting to use the thumbnail description as a template that displays several elements. One is the appropriate icon and link to the built-in Open Album/View Photo functionality. In addition to this, I would like to have other clickable elements (such as a button, or link). The Image Toolbar has some built in provisions for this, and even the thumbnail label/description seems to allow HTML elements.

However, when these elements are clicked, the built-in photo viewer starts loading (even while the link is redirecting the user or taking another action). Is it possible to make templating the thumbnail description area easier or possible to prevent the default behavior on embedded links and buttons?

There is an example of this behavior in the "online test tool" at http://nanogallery.brisbois.fr/#examples

**Comment by mudnug** [comment]
Added http://jsfiddle.net/82rk3soe/

**Comment by Kris-B** [comment]
Fixed in v5.4.0

If you still have problems, specify class 'customEventHandler' on your elements.
