### ISSUE TITLE
Any documentation on customData

### ISSUE THREAD

**Issue by macsupport** [Kris-B/nanoGALLERY#68]
I see in your jsfiddle example for the info button there is the use of customData. Any documentation on this? I am interested in how it might be used with the API method. Is there a jsfiddle to show this use with your API method?

**Comment by Kris-B** [comment]
Actually this is an item's property defined so you can store additional data.
Currently you cannot set this property directly if you use the API method to define your items.

But in the next release, I'll add support for this.

**Comment by macsupport** [comment]
That's great. I really would love to be able to add additional data. Great Plugin. I will be happy to buy a license.

**Comment by Kris-B** [comment]
Many thanks for your support! I really appreciate.

CustomData with API will be supported in v5.5.0.
Usage example: `{src: 'img.jpg', srct: 'imgt.jpg', title: 'image01', albumID:0, customData:{v1:1, v2:2} }`

The feature is already available in the current beta version: 
https://raw.githubusercontent.com/Kris-B/nanoGALLERY/master/jquery.nanogallery.js

Please let me know if this is usable for you.

**Comment by macsupport** [comment]
One would access it with `item.customData.v1`?

**Comment by Kris-B** [comment]
Exactly.

**Comment by Kris-B** [comment]
v5.5.0 has been released: you can download it at https://github.com/Kris-B/nanoGALLERY/releases/tag/v5.5.0

**Comment by vbanuelos** [comment]
@macsupport -
I was able to use JSON.stringify on an object, and attach it to the data-customdata attribute. It was then interpreted by nanogallery as an object.

![image](https://cloud.githubusercontent.com/assets/2799090/7995729/bcd5c4d0-0acd-11e5-897b-4a02260c92a1.png)

**Comment by macsupport** [comment]
Can you post your code?
