### ISSUE TITLE
Checkbox are not visible

### ISSUE THREAD

**Issue by Kwadz** [Kris-B/nanoGALLERY#70]
Hello,

After download nanoGallery, I launch demonstration.html with Firefox.
The nanoGallery3a div is supposed to show checkbox in thumbnails. However checkbox are not visible (but mouse cursor apparence change when it goes hover checkbox area). When I verify with Firebug, checkbox input are there. But they are not visible and not selectable in browser.

Same problem with IE, Firefox and Chrome on Windows and Mac OS X. But it works with all browsers on [JSFiddle](http://jsfiddle.net/eqv78jck/23/)....

Any idea ?

Thanks

**Comment by Kris-B** [comment]
Hi,
The checkbox support has been rewritten. Please check v5.5.0 which sould be released in a couple of days.

**Comment by Kris-B** [comment]
Hi, v5.5.0 has just been released. Can you please check to see if your issue is solved?

**Comment by Kwadz** [comment]
This issue is now solved ;-)

**Comment by Kris-B** [comment]
Thanks @sevarg for his work on this feature!
