### ISSUE TITLE
page counter when using openOnStart

### ISSUE THREAD

**Issue by jstranger** [Kris-B/nanoGALLERY#72]
I have been working with openOnStart as I need a simple link from with a web page to open and run a slideshow without any need for thumbnails. This now works (at least when I specify albumID and imageID), but it appears to cause the page counter to remain fixed as '1 of n'.

HTML is as follows:

    <a id="startlink" href="javascript:void(0)" style="margin-bottom: 40px;">run slide show</a>
    <div id="gallery">
            <a href=... data-ngalbumid="artist" data-ngid="1" data-ngdesc=..

Script is as follows:

        $(document).ready(function () {
            $("#startlink").click(function (e) {
                $("#gallery").nanoGallery({
                    openOnStart: "artist/1",
                    slideshowAutoStart: true,
                    colorSchemeViewer: "dark",
                    viewerToolbar: {standard: "previousButton, pageCounter, nextButton, playPauseButton, label"},
                });
            });
        });

**Comment by Kris-B** [comment]
I could not reproduce this issue.
Can you provide the full code?

**Comment by jstranger** [comment]
Hi Christophe – many thanks for your reply. The attached standalone HTML page reproduces the issue. Presumably I am missing something.

 

Regards

 

Jon

**Comment by Kris-B** [comment]
the attachment has been lost...

**Comment by jstranger** [comment]
That is odd – it is certainly attached to the message in my Sent mail – perhaps GitHub is removing it? Trying once more.

 

Jon

**Comment by jstranger** [comment]
I can’t figure out how to get GitHub to let me send an attachment, so have put the page up at http://lucknow.homeserver.com/test/slideshowtest.html

 

Jon

**Comment by Kris-B** [comment]
Hi Jon,

If you want to display 'artist/1', you also need to to define the album 'artist'.
You can do it by adding an element like this example:
`<a href="http://commandostore.net/art/artworks/890.jpg" data-ngalbumid="0" data-ngid="artist" data-ngkind="album" data-ngdesc="artist" />`
