### ISSUE TITLE
closing slideshow after openOnStart

### ISSUE THREAD

**Issue by jstranger** [Kris-B/nanoGALLERY#73]
I have been working with openOnStart as I need a simple link from with a web page to open and run a slideshow without any need for thumbnails. This now works (at least when I specify albumID and imageID), but after closing the slideshow (using either the X top R of viewer or in the toolbar) the link no longer works.

HTML is as follows:

    <a id="startlink" href="javascript:void(0)" style="margin-bottom: 40px;">run slide show</a>
    <div id="gallery">
            <a href=... data-ngalbumid="artist" data-ngid="1" data-ngdesc=..

Script is as follows:

        $(document).ready(function () {
            $("#startlink").click(function (e) {
                $("#gallery").nanoGallery({
                    openOnStart: "artist/1",
                    slideshowAutoStart: true,
                    colorSchemeViewer: "dark",
                    viewerToolbar: {standard: "previousButton, pageCounter, nextButton, playPauseButton, label"},
                });
            });
        });

**Comment by Kris-B** [comment]
Please use the API method `displayItem` instead of the option `openOnStart`.
