### ISSUE TITLE
Can the popup photo be centered? 

### ISSUE THREAD

**Issue by RickCogley** [Kris-B/nanoGALLERY#77]
Hi - thank you for nanoGallery. I have a question, if you wouldn't mind: I have it working, basically, but I wonder if I can center-align the popped up photo, like the floating tool bar is centered. 

My as-yet-unpublished site has a sidebar on the left, and the body, where the div is for nanoGallery, is in the main area to the right. 

When I click the thumbnail, the photo pops up, but inside the right area, while the toolbar does indeed get centered. I'd like to center both if possible. 

Please advise. 
Sincerely,
Rick

![nanogallery popup not centered 2015-04-30_14-40-20](https://cloud.githubusercontent.com/assets/512328/7406990/30e327ca-ef47-11e4-9e5b-f8a2b60e16f4.png)

**Comment by Kris-B** [comment]
Hi Rick,
I need to check your page. Is there a way to access your page?

**Comment by RickCogley** [comment]
@Kris-B, hi, thanks for answering. I'll publish the page soon and will come back here to give you the URL. Appreciate your help in advance. Sincerely, Rick

**Comment by RickCogley** [comment]
@Kris-B, hi, this is a temporary URL, but please see this: 

http://rick3.cogley.info/post/this-is-a-gallery-test/

If you click on one of the photos, the photo stays within the main text area, but the toolbar centers across the screen. 

Sincerely,
Rick

**Comment by RickCogley** [comment]
@Kris-B, hi, I switched the site to my main URL. 
Please see this URL instead: 
http://rick.cogley.info/post/trip-to-korea-in-feb-2015/

Kind regards,
Rick

**Comment by Kris-B** [comment]
Hi @RickCogley,
Actually, there's a conflict with your CSS file :

.content {
padding: 2rem 3rem 0;
margin-left: 25%;
}

This entry is not specific enough, so it will also apply on the "content" element in nanogallery, causing this issue.

**Comment by RickCogley** [comment]
thanks @Kris-B I'll look into doing that. Appreciate your help and time.
