### ISSUE TITLE
problem when setting "paginationMaxLinesPerPage" 

### ISSUE THREAD

**Issue by lesingerouge** [Kris-B/nanoGALLERY#79]
The gallery starts by loading only 1 thumbnail element per line (with pagination for the other elements) then when an album is clicked or the home button (Galleries) is clicked it reverts to a grid thumbnail layout.

If I do not define "paginationMaxLinesPerPage" or if I set it to 0, it puts all elements in different rows, one under the other.

My settings:
$("#nanoGallery").nanoGallery({
            items: dataobj,
            itemsSelectable: true,
            showCheckboxes: true,
            thumbnailWidth: 100,
            thumbnailHeight: 100,
            breadcrumbAutoHideTopLevel: false,
            galleryToolbarWidthAligned: false,
            maxItemsPerLine: 7,
            paginationMaxLinesPerPage: 0,
            paginationDots : false,
            thumbnailHoverEffect: 'borderLighter,imageScaleIn80',
            itemsBaseURL: "/media/thumb/get_files",
            locationHash: false,
            colorScheme: 'light'
          });

Maybe I am doing something wrong, but I cannot seem to find it.

P.S.:great gallery plugin!

**Comment by Kris-B** [comment]
Do you have a page where I can see this issue? Can you give me the URL?

**Comment by lesingerouge** [comment]
Sorry for the late reply. I am working to separate it from the rest of the app so that I can make the url public. Be right back!

**Comment by lesingerouge** [comment]
Unfortunately I cannot make that particular page public (server code too complicated), but I think the reason for the error is a conflict with some other scripts in the page. 
I have tested the library on a page with no other scripts and there are no errors. Unfortunately the other script on the page is CKeditor which means that debugging will be hell.

**Comment by Kris-B** [comment]
closed due to lack of information
