### ISSUE TITLE
only show album labels

### ISSUE THREAD

**Issue by ragefuljoe** [Kris-B/nanoGALLERY#80]
*wow im a doof. There is another L in thumbnailL1Label. lol

----
Is there some way to only show labels on album thumbnails? I tried thumbnail1Label with thumbnailLabel.display set to false, but that made everything hide.

thanks!
sendin u some beer kris

**Comment by Kris-B** [comment]
;-)

**Comment by JoROSU** [comment]
Hi, 
I use nanoGALLERY to show Flickr images. thumbnailLabel Description does not show album description.
I set thumbnailLabel: {
                    position: 'overImageOnMiddle',
                    display: true,
                    displayDescription: true,
                    hideIcons: true,
                    itemsCount: 'none',
                },
What is wrong? Thank you!

**Comment by Kris-B** [comment]
hey, nanoGALLERY is quite old now, it's time to switch to nanogallery2: https://nanogallery2.nanostudio.org/

**Comment by JoROSU** [comment]
Hi Christophe,

Thank you for advice, I migrated to nanogallery2, but I need some help.
I set NanoGALLERY to open album directly in the slider (thumbnailOpenImage),
but in nanogallery2 I can't reproduce the same behaviour.
I load Flickr albums and I want this flow: list Flickr album and when user
click on a thumbnail the slider with the rest images is shown (I DON'T want
to show list of album's images and on the click show slider).
Can you help me to set this, please? You can see my solution on
https://jozebradesign.bitbucket.io/bojansipka/work.html
Responsive behaviour is different, I show a list of the album's images,
without the slider, but it is ok, I know to set it.

Thank you,
Jovana

**Comment by Kris-B** [comment]
Hi Jovana,
The correct option is `thumbnailAlbumDisplayImage`, it will be fixed in the next nanogallery2 release

**Comment by JoROSU** [comment]
P. S.  nanoGallery2 is really great solution.  :)

**Comment by Kris-B** [comment]
I'll try to release it next week
