### ISSUE TITLE
How to use fnThumbnailOpen?

### ISSUE THREAD

**Issue by vbanuelos** [Kris-B/nanoGALLERY#82]
An example added to http://nanogallery.brisbois.fr/#docHelpers would be beneficial.

**Comment by macsupport** [comment]
Love that you added this new function but we need at least a simple demo of how one might integrate with another lightbox.

**Comment by Kris-B** [comment]
Here's a sample: http://codepen.io/Kris-B/pen/BNOWEK

items= arrays containing the liste of images. index 0 is the selected image.
Some properties:
- items[n].title: title
- items[n].src: image url
- items[n].thumbImg().src: thumbnail url

Hope this will help.
