### ISSUE TITLE
Link large images to a URL

### ISSUE THREAD

**Issue by ghalusa** [Kris-B/nanoGALLERY#84]
Hi Kris. First, let me say that I'm loving nanoGALLERY. Question... in image gallery view (large images), I'm trying to link the image to a URL, instead of having it go to the next or previous image. As far as I can tell, this is not possible to do natively, in nanoGALLERY. Am I right? Or, is there some way to override the next/previous functionality when clicking on full size images?

BTW, I also left a comment on Disqus:
http://disq.us/8nrhso

And a jsfiddle:
http://jsfiddle.net/ghalusa/wnh3zhcr/

**Comment by ghalusa** [comment]
Kris... I ended up forking and adding the functionality myself. Now, large images can have a destination url applied to them via the "data-nglargeimagedest" attribute. You may close this issue if you wish :)

My fork:
https://github.com/ghalusa/nanoGALLERY

**Comment by Kris-B** [comment]
Do not hesitate to make a PR, so everyone can use it.
Thanks.
