### ISSUE TITLE
Album Id in picasa/google+/photo provider

### ISSUE THREAD

**Issue by dcoeurjo** [Kris-B/nanoGALLERY#89]
Apparently, google has changed is API/url system for albums  and I don't know how to get the id of brand new albums. 
Any idea to connect these albums to nanoGallery ? 
thx

**Comment by TuSKan** [comment]
It's works, at least for me. My problem was just change the **?** by **&**.

https://plus.google.com/u/0/photos/ *USERID* /albums/ *ALBUMID* **?** authkey= *key*: 

change *ALBUMID* **?** authkey= *key* to *ALBUMID* **&** authkey= *key*.

Try it.

**Comment by dcoeurjo** [comment]
Actually, my new album has an URL like this: 

https://photos.google.com/album/AF1QipMabOaXO744r3eCkYZBPGITeMO2tsFhXb55VyeG

And the url is also different when accessing from google+

**Comment by AlexRed** [comment]
You can use only the albums that are on Google+ Photos and not those on the new service Google Photos.
To visit the old interface Google+ Photos : https://plus.google.com/u/0/photos/highlights
To visit the new interface Google Photos thi is the link: https://photos.google.com/collections

In view of the gradual abandonment of Google+ Photos by Google, it is expected to be used also the new Google Photos but you need to make the new albums created by Google Photos "public".

You can make public your new album created with Google Photos from Google+ Photos or from Picasa by accessing this link: https://picasaweb.google.com/home
Selecting the album you must access the "Actions" menu and change the "Album Properties" setting "Visibility" -> "Public on the web".

**Comment by dcoeurjo** [comment]
Thanks a lot @AlexRed & @TuSKan. Browsing my album from the old google+Photos interface solves my problem.
(however, from the new interface, I cannot get the albumId --and yes, my album is "public"--). 

thanks again, I close this issue..

**Comment by Kris-B** [comment]
Hoping the Google API will be extended to support Google Photos in a near future...

Many thanks @AlexRed for the procedure!
I'll add it to the documentation.

**Comment by jancona** [comment]
It looks like the old G+ interface is no longer available, but if you visit this URL `https://picasaweb.google.com/data/feed/api/user/<userId>`, you'll get an Atom XML feed of your albums. (Depending on your browser, you may need to do a _View Source_ to see the XML.) If you search through the XML for the album name you're interested in, you'll find a link tag nearby that includes the albumId, something like `https://picasaweb.google.com/data/feed/api/user/<userId>/albumid/<albumId>`. The albumId there works.

Hope this helps, and that Google gets its Photos API act together soon.

**Comment by Kris-B** [comment]
thanks.

I'm trying to make it easier to retrieve the userID and the albums IDs.

So I just added the button ```Retrieve your Google+ informations``` on the documentation: http://nanogallery.brisbois.fr/#docPicasa

**Comment by webrunner74** [comment]
Thanks jancona, you saved my day, looks that this feed is the last way to get our old albums ids. I needed those ids for http://plusgallery.net jquery plugin, equivalent I guess to nanogallery...

**Comment by dkutcher** [comment]
This method might help: http://www.blogxpertise.com/2016/07/user-id-album-id-and-jsonrss-feed-url.html

Essentially getting your User ID, then pulling up a JSON listing of all of your public albums to find the album ID.
