### ISSUE TITLE
Highly Touch Sensitive Galleries

### ISSUE THREAD

**Issue by Ecksters** [Kris-B/nanoGALLERY#93]
It appears that the gallery is overly sensitive to touch by default, I have to touch extremely lightly to avoid clicking into images in the album when scrolling through a large album. I find it particularly noticeable when trying to do little flicks to scroll.

Maybe a fix similar to this might do it?
http://stackoverflow.com/questions/4095059/android-how-to-make-ontouch-work-like-onclick

**Comment by Kris-B** [comment]
Can you give more details? And maybe with a live url?
