### ISSUE TITLE
nanoGallery site Demo broken for inline element examples

### ISSUE THREAD

**Issue by macsupport** [Kris-B/nanoGALLERY#96]
Choosing inline elements in the dropdown menu on your site gives the following error and fails:

DemoSetnanogallery.brisbois.fr:3711TypeError: CodePenEmbed.showCodePenEmbeds is not a function. (In 'CodePenEmbed.showCodePenEmbeds()', 'CodePenEmbed.showCodePenEmbeds' is undefined)

**Comment by Kris-B** [comment]
Thansk for the notice!

CodePens are fixed now but they're still incorrectly embedded in the demo page. I need to find a solution for this also...

**Comment by Kris-B** [comment]
fixed
