### ISSUE TITLE
ThumbnailL1 issue?

### ISSUE THREAD

**Issue by klous-1** [Kris-B/nanoGALLERY#97]
Hi Christophe,

I'm not sure but it looks to me like there is some issue with thumbnailL1Height/Width.  The thumbs are not displaying correctly, just small slits (may depend on settings/sizes used).

I've just updated from v5.4 to 5.9, and then also tried an old jsfiddle of yours which has v5.7.  v5.4 is/was working fine, but 5.7 and 5.9 seem to have this issue.

Check out the updated fiddle here which shows the problem:
http://jsfiddle.net/99xLegdk/

**Comment by klous-1** [comment]
OK, it seems to be a problem with 'auto' option in combination with thumbnailL1 settings....oddly the Level 1 images display okay.  Take out auto or L1 setting and it works okay.

**Comment by Kris-B** [comment]
Hey! Actually it is an issue with 'auto' and Picasa storage.
The 'auto' value implies the thumbnail image size (width and height) to be known. But the  Picasa/Google+ API returns incorrect values for the first level (albums).
So nG needs to wait until the thumbnail images are loaded to retrieve their correct size and then the layout can be rendered.

So long for the method...

I check the fiddle http://jsfiddle.net/99xLegdk/ : I see the small slits and after a small delay, thumbnails are displayed correctly.

In your case : the small slits are never replaced by the correct thumbnails?

**Comment by klous-1** [comment]
Level1 is okay (albums) but it is the photos within the albums which is the problem....slits remain permanently, in the fiddle too (it's not like this for you?).

Like I say, v5.4 was no problem and my gallery is fine with thsi version, so something has changed.(http://www.talesfromthesaddle.com/photos)

**Comment by Kris-B** [comment]
ok, found this issue.
please check v5.9.1

**Comment by klous-1** [comment]
Thanks Christophe!  Works a treat now! :+1:

**Comment by Kris-B** [comment]
;-)
