### ISSUE TITLE
Is there a way to set a minimum number of items to be shown in a row of the gallery?

### ISSUE THREAD

**Issue by dcyoung3455** [Kris-B/nanoGALLERY#99]

**Comment by Kris-B** [comment]
Hi Donna!
You cannot, but for the same purpose you can set a min-width to the container of the gallery.

**Comment by dcyoung3455** [comment]
Hi Christophe,

I actually got the affect I wanted by setting the thumbnail with to 250 and
the height to "auto".

If I might ask another question.  I know you get pagination kind of "for
free" when using PIcasa/Google+/Flickr storage.  I guess if I wanted to do
pagination for inline image links I need to handle all the pagination using
code.  Right?

I might try to migrate to one of those storage systems in the future.

Thank you for all your help.

Best regards,
             Donna
